// Generated by CoffeeScript 1.7.1
(function() {
  var Lexer, lexer, parser, pkg, stringifier, toString, whitelist;

  toString = Object.prototype.toString;

  whitelist = require('./whitelist');

  parser = require('./parser');

  stringifier = require('./stringifier');

  pkg = require('../package.json');

  Lexer = (function() {
    var _trimStruct;

    _trimStruct = function(structure) {
      var tmpNewLines, _struct;
      _struct = [];
      tmpNewLines = '';
      structure.forEach(function(struct, i) {
        if (toString.call(struct) === '[object String]') {
          if (struct.trim().length === 0) {
            if (!_struct.length) {
              return;
            }
            return tmpNewLines += struct;
          }
        }
        if (tmpNewLines.length) {
          _struct.push(tmpNewLines);
          tmpNewLines = '';
        }
        return _struct.push(struct);
      });
      return _struct;
    };

    function Lexer(structure) {
      this.structure = structure;
      if (toString.call(this.structure) !== '[object Array]') {
        this.structure = [this.structure];
      }
      this.structure = _trimStruct(this.structure);
    }

    Lexer.prototype.html = function() {
      return lexer.stringifier.toHtml(this.structure);
    };

    Lexer.prototype.text = function() {
      return lexer.stringifier.toText(this.structure).trim();
    };

    Lexer.prototype.toJSON = function() {
      return this.structure;
    };

    Lexer.prototype.isValid = function() {
      return this.structure.every(function(obj) {
        return toString.call(obj) === '[object String]' || lexer.whitelist[obj != null ? obj.type : void 0];
      });
    };

    return Lexer;

  })();

  lexer = function(structure) {
    return new Lexer(structure);
  };

  lexer.name = 'lexer';

  lexer.version = pkg.version;

  lexer.whitelist = whitelist;

  lexer.parser = parser;

  lexer.stringifier = stringifier;

  lexer.createElement = function(type, text, props) {
    var ele, k, v;
    if (!whitelist[type]) {
      return text;
    }
    ele = {
      type: type,
      text: text
    };
    for (k in props) {
      v = props[k];
      ele[k] = v;
    }
    return ele;
  };

  lexer.parseDOM = function() {
    var structure;
    structure = lexer.parser.parseDOM.apply(lexer.parser, arguments);
    return new Lexer(structure);
  };

  module.exports = lexer;

  if (typeof window !== "undefined" && window !== null) {
    window.lexer = lexer;
  }

}).call(this);
