// Generated by CoffeeScript 1.7.1
(function() {
  var parseDOM, whitelist;

  whitelist = require('./whitelist');

  parseDOM = function(nodes) {
    var _i, _ref, _results;
    return (function() {
      _results = [];
      for (var _i = 0, _ref = nodes.length; 0 <= _ref ? _i < _ref : _i > _ref; 0 <= _ref ? _i++ : _i--){ _results.push(_i); }
      return _results;
    }).apply(this).map(function(i) {
      var node, obj, tagName, _i, _ref, _ref1, _results;
      node = nodes[i];
      tagName = node.tagName;
      if (tagName != null) {
        tagName = tagName.toLowerCase();
      }
      if (!((tagName != null) && whitelist[tagName])) {
        return node.textContent;
      }
      obj = {
        type: tagName,
        text: node.textContent
      };
      obj.data = {};
      (function() {
        _results = [];
        for (var _i = 0, _ref = (_ref1 = node.attributes) != null ? _ref1.length : void 0; 0 <= _ref ? _i < _ref : _i > _ref; 0 <= _ref ? _i++ : _i--){ _results.push(_i); }
        return _results;
      }).apply(this).forEach(function(i) {
        var attr, key, prefix, _ref;
        attr = node.attributes[i];
        _ref = attr.name.split('-'), prefix = _ref[0], key = _ref[1];
        if (prefix === 'data' && (key != null)) {
          return obj.data[key] = attr.value;
        }
      });
      return obj;
    });
  };

  module.exports = {
    parseDOM: parseDOM
  };

}).call(this);
