// Generated by CoffeeScript 1.8.0
(function() {
  var stringifierMap, toHtml, toString, toText, whitelist, _entities, _markLink;

  whitelist = require('./whitelist');

  toString = Object.prototype.toString;

  _markLink = function(str) {
    return str.replace(/(http(s)?:\/\/[^\s]+)/ig, '<a href="$1" target="_blank">$1</a>');
  };

  _entities = function(str) {
    return str.replace(/[&<>"']/g, function(code) {
      return "&" + {
        "&": "amp",
        "<": "lt",
        ">": "gt",
        '"': "quot",
        "'": "apos"
      }[code] + ";";
    });
  };

  stringifierMap = {
    "default": function(node) {
      var attrs, data, k, text, type, v;
      type = node.type, text = node.text, data = node.data;
      data || (data = {});
      attrs = (function() {
        var _results;
        _results = [];
        for (k in data) {
          v = data[k];
          _results.push("data-" + k + "=\"" + v + "\"");
        }
        return _results;
      })();
      return "<" + type + " " + (attrs.join(' ')) + ">" + (_entities(text)) + "</" + type + ">";
    },
    mention: function(node) {
      return stringifierMap["default"](node);
    },
    link: function(node) {
      var href, text, type;
      type = node.type, href = node.href, text = node.text;
      return "<a href=\"" + href + "\" class=\"lexer-link\" rel=\"noreferrer\" target=\"_blank\">" + (_entities(text)) + "</a>";
    },
    highlight: function(node) {
      var text, type;
      type = node.type, text = node.text;
      return "<span class=\"lexer-highlight\">" + text + "</span>";
    },
    text: function(node) {
      var text;
      text = node.text || node;
      return _markLink(_entities(text));
    }
  };

  toHtml = function(structure) {
    return structure.map(function(node) {
      var data, text, type;
      if (toString.call(node) === '[object String]') {
        return stringifierMap.text(node);
      }
      if (node == null) {
        return '';
      }
      type = node.type, text = node.text, data = node.data;
      if (!(whitelist[type] && typeof stringifierMap[type] === 'function')) {
        return '';
      }
      return stringifierMap[type](node);
    }).join('');
  };

  toText = function(structure) {
    return structure.map(function(node) {
      var data, text, type;
      if (toString.call(node) === '[object String]') {
        return node;
      }
      if (node == null) {
        return '';
      }
      type = node.type, text = node.text, data = node.data;
      if (!whitelist[type]) {
        return '';
      }
      return text || '';
    }).join('');
  };

  module.exports = {
    toHtml: toHtml,
    toText: toText
  };

}).call(this);
